name: Metrics
on:
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # GitHub Access Token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: krampus-nuggets
          template: classic
          base: header, activity, community, repositories, metadata
          config_octicon: yes
          config_order: base.header, topics
          config_padding: 0, 8 + 10%
          config_timezone: Africa/Johannesburg
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 3
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_gists: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_topics: yes
          plugin_topics_limit: 30
          plugin_topics_mode: icons
          plugin_topics_sort: stars
